### PR TITLE
add Sony Xperia Z3

### PR DESCRIPTION
**Pull request by Anik1199**

### CODE REVIEW

**Comment by DC07** [comment]
Will be merged only if you have the device.

**Comment by Anik1199** [comment]
i don't have this device

**Comment by C-Aniruddh** [comment]
@Anik1199 Is this properly tested?

**Comment by Anik1199** [comment]
no sound

**Comment by C-Aniruddh** [comment]
@Anik1199 kindly fix all the bugs.

**Comment by Anik1199** [comment]
hangout plz

**Pull request closed without merging**
