### PR TITLE
new devices

### PR DESCRIPTION
**Pull request by akhilnarang**
Android one-both variants
Sony Xperia SP
Don't merge yet :P, haven't made a build for android one yet

### CODE REVIEW

**Comment by C-Aniruddh** [comment]
Do you own the devices?

**Comment by akhilnarang** [comment]
I own an android one device, not huashan
But the builds I make for huashan are completely stable, just one bug, which is a cm-12.1 bug of the device
I'll make flex build for android one tomorrow

**Comment by DC07** [comment]
then let huashan be unofficial, regarding sprout if you own the device we will get it official.

**Comment by akhilnarang** [comment]
Yes, I own sprout, I'm gonna make the build today evening

**Comment by akhilnarang** [comment]
@C-Aniruddh  @arnavgosain @DC07 
http://forum.xda-developers.com/crossdevice-dev/android-one-crossdevice-development-original-android-development/sprout4-flexos-t3108249#post60728328

**Comment by DC07** [comment]
Great.

**Pull request merged**
